BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '../Poshify/Poshify.psd1') -Force

    function New-ThemeFile {
        param([string]$Directory, [string[]]$FileName)
        New-Item -ItemType Directory -Path $Directory -Force | Out-Null
        foreach ($file in $FileName) {
            Set-Content -LiteralPath (Join-Path $Directory $file) -Value '{}'
        }
    }
}

AfterAll {
    Remove-Module Poshify -Force -ErrorAction SilentlyContinue
}

Describe 'Poshify' {
    BeforeEach {
        $script:home_ = Join-Path $TestDrive 'home/.poshthemes'
        $script:bundled = Join-Path $TestDrive 'oh-my-posh/themes'
        $script:profilePath = Join-Path $TestDrive 'Documents/PowerShell/profile.ps1'
        Remove-Item -Path (Join-Path $TestDrive '*') -Recurse -Force -ErrorAction SilentlyContinue

        $script:savedThemesPath = $env:POSH_THEMES_PATH
        $env:POSH_THEMES_PATH = $script:bundled

        InModuleScope Poshify -Parameters @{ Path = $script:home_ } {
            param($Path)
            $script:PoshifyHome = $Path
        }
        Mock Get-PoshifyProfileTarget -ModuleName Poshify {
            [PSCustomObject]@{ Edition = 'Core'; Path = (Join-Path $TestDrive 'Documents/PowerShell/profile.ps1'); IsCurrent = $true }
        }
        Mock Get-PoshifyExecutionPolicy -ModuleName Poshify { 'RemoteSigned' }
        Mock Get-OhMyPoshCommand -ModuleName Poshify { [PSCustomObject]@{ Name = 'oh-my-posh' } }
        Mock Invoke-PoshifyInitScript -ModuleName Poshify { }

        # Folder themes are looked up from the current folder; keep real .poshify/.ompconfig files out of it
        Push-Location -LiteralPath $TestDrive

        # No network in tests: online lookups find nothing unless a context mocks them
        Mock Invoke-RestMethod -ModuleName Poshify { @() }
        Mock Invoke-WebRequest -ModuleName Poshify { throw 'Network access is disabled in tests' }
    }

    AfterEach {
        Pop-Location
        $env:POSH_THEMES_PATH = $script:savedThemesPath
    }

    Context 'Merge-PoshifyProfileBlock' {
        It 'appends the block after existing content' {
            InModuleScope Poshify {
                $result = Merge-PoshifyProfileBlock -Content "Import-Module Terminal-Icons`n"
                $result | Should -Match '^Import-Module Terminal-Icons\n\n# >>> poshify >>>\n'
                $result | Should -Match '# <<< poshify <<<\n$'
            }
        }

        It 'is idempotent' {
            InModuleScope Poshify {
                $once = Merge-PoshifyProfileBlock -Content "Import-Module Terminal-Icons`n"
                Merge-PoshifyProfileBlock -Content $once | Should -BeExactly $once
            }
        }

        It 'keeps the block where the user moved it and drops duplicates' {
            InModuleScope Poshify {
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                $content = "# top`n$block`n# middle`n$block`n# bottom`n"
                Merge-PoshifyProfileBlock -Content $content | Should -BeExactly "# top`n$block`n# middle`n# bottom`n"
            }
        }

        It 'replaces an outdated block in place' {
            InModuleScope Poshify {
                $content = "# top`n# >>> poshify >>>`nold stuff`n# <<< poshify <<<`n# bottom`n"
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                Merge-PoshifyProfileBlock -Content $content | Should -BeExactly "# top`n$block`n# bottom`n"
            }
        }

        It 'migrates complete and partially-removed blocks written by Poshify 1.0' {
            InModuleScope Poshify {
                $legacy = "# Poshify Theme - Generated by Poshify Module`n# Theme: agnoster`n# Generated on: 2025-01-01 10:00:00`n`noh-my-posh init pwsh --config `"C:\t\agnoster.omp.json`" | Invoke-Expression"
                # What the 1.0 cleanup regex left behind: the header line removed, the rest kept
                $leftover = "# Theme: atomic`n# Generated on: 2025-01-02 10:00:00`n`noh-my-posh init pwsh --config `"C:\t\atomic.omp.json`" | Invoke-Expression"
                $content = "Import-Module posh-git`n`n$leftover`n`n$legacy`n"

                $result = Merge-PoshifyProfileBlock -Content $content -Remove
                $result | Should -BeExactly "Import-Module posh-git`n"
            }
        }

        It 'only removes its own block and leaves other oh-my-posh setup intact' {
            InModuleScope Poshify {
                $foreign = '& ([ScriptBlock]::Create((oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json") -join "`n"))'
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                Merge-PoshifyProfileBlock -Content "$foreign`n`n$block`n" -Remove | Should -BeExactly "$foreign`n"
            }
        }

        It 'preserves CRLF line endings' {
            InModuleScope Poshify {
                $result = Merge-PoshifyProfileBlock -Content "Import-Module posh-git`r`n"
                ($result -replace "`r`n", '') | Should -Not -Match "`n"
            }
        }

        It 'generates a block that runs cleanly when no theme is selected' {
            InModuleScope Poshify {
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                { & ([scriptblock]::Create($block)) } | Should -Not -Throw
            }
        }
    }

    Context 'Get-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'custom.omp.yaml'
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.toml', 'readme.md'
        }

        It 'lists themes from Poshify and oh-my-posh, with downloads shadowing bundled themes' {
            $themes = Get-PoshifyTheme
            $themes.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic', 'custom')
            ($themes | Where-Object Name -eq 'agnoster').Source | Should -Be 'Poshify'
        }

        It 'prefers an exact name match over partial matches' {
            $result = @(Get-PoshifyTheme -Name 'agnoster')
            $result.Count | Should -Be 1
            $result[0].Name | Should -Be 'agnoster'
        }

        It 'falls back to substring and wildcard matching' {
            @(Get-PoshifyTheme -Name 'plus').Name | Should -Be 'agnosterplus'
            @(Get-PoshifyTheme -Name 'a*').Count | Should -Be 3
        }

        It 'writes an error when nothing matches' {
            Get-PoshifyTheme -Name 'nope' -ErrorVariable err -ErrorAction SilentlyContinue | Should -BeNullOrEmpty
            $err | Should -Not -BeNullOrEmpty
        }

        It 'tolerates a POSH_THEMES_PATH that does not exist' {
            $env:POSH_THEMES_PATH = Join-Path $TestDrive 'missing'
            { Get-PoshifyTheme -ErrorAction Stop } | Should -Not -Throw
            (Get-PoshifyTheme).Name | Should -Be @('agnoster', 'custom')
        }
    }

    Context 'Set-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.json'
        }

        It 'creates the profile and its directory when missing' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $script:profilePath | Should -Exist
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match '# >>> poshify >>>'
        }

        It 'records the selection and marks the theme as current' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be (Join-Path $script:bundled 'agnoster.omp.json')
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'agnoster'
        }

        It 'does not rewrite the profile when switching themes' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $before = Get-Content -LiteralPath $script:profilePath -Raw
            (Get-Item $script:profilePath).LastWriteTime = [datetime]'2000-01-01'

            Set-PoshifyTheme -Name 'atomic' -NoApply

            Get-Content -LiteralPath $script:profilePath -Raw | Should -BeExactly $before
            (Get-Item $script:profilePath).LastWriteTime | Should -Be ([datetime]'2000-01-01')
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'atomic'
        }

        It 'keeps existing profile content and encoding' {
            New-Item -ItemType Directory -Path (Split-Path $script:profilePath) -Force | Out-Null
            $original = "Write-Output 'héllo wörld'`r`n"
            [IO.File]::WriteAllText($script:profilePath, $original, (New-Object Text.UTF8Encoding($false)))

            Set-PoshifyTheme -Name 'agnoster' -NoApply

            $bytes = [IO.File]::ReadAllBytes($script:profilePath)
            $bytes[0] | Should -Not -Be 0xEF
            $text = [IO.File]::ReadAllText($script:profilePath)
            $text | Should -BeLike "$original`r`n# >>> poshify >>>*"
        }

        It 'refuses an ambiguous partial name instead of guessing' {
            Set-PoshifyTheme -Name 'agnost' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'accepts themes from the pipeline' {
            Get-PoshifyTheme -Name 'atomic' | Set-PoshifyTheme -NoApply
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'atomic'
        }

        It 'accepts a direct path' {
            $custom = Join-Path $TestDrive 'mine.omp.json'
            Set-Content -LiteralPath $custom -Value '{}'
            Set-PoshifyTheme -ThemePath $custom -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be $custom
        }

        It 'changes nothing with -WhatIf' {
            Set-PoshifyTheme -Name 'agnoster' -WhatIf
            $script:profilePath | Should -Not -Exist
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'fails when oh-my-posh is not installed' {
            Mock Get-OhMyPoshCommand -ModuleName Poshify { }
            Set-PoshifyTheme -Name 'agnoster' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'not installed'
            $script:profilePath | Should -Not -Exist
        }
    }

    Context 'Reset-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            New-Item -ItemType Directory -Path (Split-Path $script:profilePath) -Force | Out-Null
            Set-Content -LiteralPath $script:profilePath -Value 'Import-Module posh-git'
            Set-PoshifyTheme -Name 'agnoster' -NoApply
        }

        It 'removes the block and selection, keeping the rest of the profile' {
            Reset-PoshifyTheme
            (Get-Content -LiteralPath $script:profilePath -Raw).Trim() | Should -BeExactly 'Import-Module posh-git'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'warns about oh-my-posh setup it did not create' {
            Add-Content -LiteralPath $script:profilePath -Value 'oh-my-posh init pwsh | Invoke-Expression'
            Reset-PoshifyTheme -WarningVariable warnings -WarningAction SilentlyContinue
            "$warnings" | Should -Match 'outside Poshify'
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match 'oh-my-posh init pwsh'
        }

        It 'changes nothing with -WhatIf' {
            $before = Get-Content -LiteralPath $script:profilePath -Raw
            Reset-PoshifyTheme -WhatIf
            Get-Content -LiteralPath $script:profilePath -Raw | Should -BeExactly $before
        }
    }


    Context 'Find-PoshifyTheme' {
        BeforeEach {
            Mock Invoke-RestMethod -ModuleName Poshify {
                @(
                    [PSCustomObject]@{ name = 'agnoster.omp.json'; size = 2048; download_url = 'https://example.test/agnoster.omp.json'; sha = 'a1' }
                    [PSCustomObject]@{ name = 'agnosterplus.omp.json'; size = 2048; download_url = 'https://example.test/agnosterplus.omp.json'; sha = 'b2' }
                    [PSCustomObject]@{ name = 'atomic.omp.yaml'; size = 1024; download_url = 'https://example.test/atomic.omp.yaml'; sha = 'c3' }
                    [PSCustomObject]@{ name = 'schema.json'; size = 10; download_url = 'https://example.test/schema.json'; sha = 'd4' }
                )
            }
        }

        It 'returns only theme files' {
            (Find-PoshifyTheme).Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
        }

        It 'returns a single match' {
            $result = @(Find-PoshifyTheme -Name 'atomic')
            $result.Count | Should -Be 1
            $result[0].FileName | Should -Be 'atomic.omp.yaml'
            $result[0].Sha | Should -Be 'c3'
        }

        It 'reuses the cached list until -ForceRefresh' {
            Find-PoshifyTheme | Out-Null
            $cached = Find-PoshifyTheme
            Should -Invoke Invoke-RestMethod -ModuleName Poshify -Times 1 -Exactly
            $cached.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
            $cached[0].PSObject.TypeNames | Should -Contain 'Poshify.OnlineTheme'

            Find-PoshifyTheme -ForceRefresh | Out-Null
            Should -Invoke Invoke-RestMethod -ModuleName Poshify -Times 2 -Exactly
        }

        It 'refetches once the cache is older than an hour' {
            Find-PoshifyTheme | Out-Null
            $cacheFile = Join-Path $script:home_ '.cache/themes.json'
            $cache = Get-Content $cacheFile -Raw | ConvertFrom-Json
            $cache.CachedAt = [datetime]::UtcNow.AddHours(-2).ToString('o')
            $cache | ConvertTo-Json -Depth 3 | Set-Content $cacheFile

            Find-PoshifyTheme | Out-Null
            Should -Invoke Invoke-RestMethod -ModuleName Poshify -Times 2 -Exactly
        }

        It 'falls back to a stale cache when GitHub is unreachable' {
            Find-PoshifyTheme | Out-Null
            Mock Invoke-RestMethod -ModuleName Poshify { throw 'No such host is known' }

            $result = Find-PoshifyTheme -ForceRefresh -WarningVariable warnings -WarningAction SilentlyContinue
            $result.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
            "$warnings" | Should -Match 'cached'
        }

        It 'reports GitHub rate limiting clearly' {
            Mock Invoke-RestMethod -ModuleName Poshify { throw 'API rate limit exceeded for 1.2.3.4' }
            Find-PoshifyTheme -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'rate limit reached'
        }
    }

    Context 'Install-PoshifyTheme' {
        BeforeEach {
            Mock Get-PoshifyOnlineThemeList -ModuleName Poshify {
                foreach ($name in 'agnoster', 'agnosterplus', 'atomic') {
                    [PSCustomObject]@{ Name = $name; FileName = "$name.omp.json"; DownloadUrl = "https://example.test/$name.omp.json"; Sha = 'x' }
                }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{}' }
        }

        It 'downloads the exact match without prompting' {
            $theme = Install-PoshifyTheme -Name 'agnoster'
            $theme.Name | Should -Be 'agnoster'
            $theme.Source | Should -Be 'Poshify'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 1 -Exactly
        }

        It 'errors on an ambiguous name instead of prompting' {
            Install-PoshifyTheme -Name 'agnost' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly
        }

        It 'returns an existing local theme unless -Force is used' {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            (Install-PoshifyTheme -Name 'agnoster' -WarningAction SilentlyContinue).Source | Should -Be 'oh-my-posh'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly

            (Install-PoshifyTheme -Name 'agnoster' -Force).Source | Should -Be 'Poshify'
        }

        It 'is not fooled by a local theme that only contains the name' {
            New-ThemeFile -Directory $script:bundled -FileName 'agnosterplus.omp.json'
            (Install-PoshifyTheme -Name 'agnoster').Name | Should -Be 'agnoster'
        }

        It 'leaves no partial file when the download fails' {
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value 'partial'; throw 'connection reset' }
            Install-PoshifyTheme -Name 'atomic' -ErrorAction SilentlyContinue
            Get-ChildItem -LiteralPath $script:home_ | Should -BeNullOrEmpty
        }

        It 'queries GitHub once for piped themes' {
            [PSCustomObject]@{ Name = 'agnoster' }, [PSCustomObject]@{ Name = 'atomic' } | Install-PoshifyTheme
            Should -Invoke Get-PoshifyOnlineThemeList -ModuleName Poshify -Times 1 -Exactly
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 2 -Exactly
        }
    }

    Context 'Update-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'atomic.omp.json', 'retired.omp.json'
            New-ThemeFile -Directory $script:bundled -FileName 'bundled.omp.json'
            $script:upToDateSha = InModuleScope Poshify -Parameters @{ Path = (Join-Path $script:home_ 'agnoster.omp.json') } {
                param($Path)
                Get-PoshifyGitBlobSha -Path $Path
            }
            Mock Get-PoshifyOnlineThemeList -ModuleName Poshify -ParameterFilter { $ForceRefresh } {
                [PSCustomObject]@{ Name = 'agnoster'; FileName = 'agnoster.omp.json'; DownloadUrl = 'https://example.test/agnoster.omp.json'; Sha = $script:upToDateSha }
                [PSCustomObject]@{ Name = 'atomic'; FileName = 'atomic.omp.json'; DownloadUrl = 'https://example.test/atomic.omp.json'; Sha = 'changed' }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{"new": true}' }
        }

        It 'matches git blob hashes reported by GitHub' {
            # Well-known `git hash-object` result for "hello world\n"
            $file = Join-Path $TestDrive 'hello.txt'
            [IO.File]::WriteAllText($file, "hello world`n")
            InModuleScope Poshify -Parameters @{ Path = $file } {
                param($Path)
                Get-PoshifyGitBlobSha -Path $Path
            } | Should -Be '3b18e512dba79e4c8300dd08aeb37f8e728b8dad'
        }

        It 'downloads only themes that changed online' {
            $updated = @(Update-PoshifyTheme -All -WarningAction SilentlyContinue)
            $updated.Name | Should -Be 'atomic'
            Get-Content (Join-Path $script:home_ 'atomic.omp.json') -Raw | Should -Match 'new'
            Get-Content (Join-Path $script:home_ 'agnoster.omp.json') -Raw | Should -Not -Match 'new'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 1 -Exactly
        }

        It 'keeps themes that were removed upstream and warns' {
            Update-PoshifyTheme -Name 'retired' -WarningVariable warnings -WarningAction SilentlyContinue
            "$warnings" | Should -Match 'no longer in the oh-my-posh repository'
            Join-Path $script:home_ 'retired.omp.json' | Should -Exist
        }

        It 'only updates themes installed by Poshify' {
            Update-PoshifyTheme -Name 'bundled' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'installed by Poshify'
            Should -Invoke Get-PoshifyOnlineThemeList -ModuleName Poshify -Times 0 -Exactly
        }

        It 'changes nothing with -WhatIf' {
            Update-PoshifyTheme -Name 'atomic' -WhatIf
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly
        }
    }

    Context 'Remove-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'agnosterplus.omp.json'
            New-ThemeFile -Directory $script:bundled -FileName 'atomic.omp.json'
        }

        It 'removes a downloaded theme' {
            Remove-PoshifyTheme -Name 'agnoster'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Not -Exist
            Join-Path $script:home_ 'agnosterplus.omp.json' | Should -Exist
        }

        It 'requires the exact name' {
            Remove-PoshifyTheme -Name 'plus' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'exact theme name'
            Join-Path $script:home_ 'agnosterplus.omp.json' | Should -Exist
        }

        It 'refuses to remove themes bundled with oh-my-posh' {
            Remove-PoshifyTheme -Name 'atomic' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'bundled with oh-my-posh'
            Join-Path $script:bundled 'atomic.omp.json' | Should -Exist
        }

        It 'protects the current theme unless -Force is used' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Remove-PoshifyTheme -Name 'agnoster' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'current theme'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist

            Remove-PoshifyTheme -Name 'agnoster' -Force -WarningAction SilentlyContinue
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Not -Exist
        }

        It 'changes nothing with -WhatIf' {
            Remove-PoshifyTheme -Name 'agnoster' -WhatIf
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist
        }
    }

    Context 'Get-PoshifyCurrentTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            $script:custom = Join-Path $TestDrive 'mine.omp.json'
            Set-Content -LiteralPath $script:custom -Value '{}'
        }

        It 'returns nothing when no theme is selected' {
            Get-PoshifyCurrentTheme | Should -BeNullOrEmpty
        }

        It 'returns the selected theme' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $current = Get-PoshifyCurrentTheme
            $current.Name | Should -Be 'agnoster'
            $current.Current | Should -BeTrue
        }

        It 'reports themes set by path as custom' {
            Set-PoshifyTheme -ThemePath $script:custom -NoApply
            $current = Get-PoshifyCurrentTheme
            $current.Name | Should -Be 'mine'
            $current.Source | Should -Be 'Custom'
        }

        It 'warns when the selected file is gone' {
            Set-PoshifyTheme -ThemePath $script:custom -NoApply
            [IO.File]::Delete($script:custom)

            Get-PoshifyCurrentTheme -WarningVariable warnings -WarningAction SilentlyContinue | Should -BeNullOrEmpty
            "$warnings" | Should -Match 'no longer exists'
        }
    }

    Context 'Favorites' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.json'
        }

        It 'keeps a proper list when adding several favorites' {
            Add-PoshifyFavorite -Name 'agnoster'
            Add-PoshifyFavorite -Name 'atomic'
            Add-PoshifyFavorite -Name 'agnoster'

            Get-PoshifyFavorite | Should -Be @('agnoster', 'atomic')
        }

        It 'stores a single favorite as a JSON list' {
            Add-PoshifyFavorite -Name 'atomic'
            (Get-Content (Join-Path $script:home_ '.favorites.json') -Raw).Trim() | Should -Match '^\['
        }

        It 'stores the exact theme name for a unique partial match' {
            Add-PoshifyFavorite -Name 'plus'
            Get-PoshifyFavorite | Should -Be 'agnosterplus'
        }

        It 'rejects an ambiguous name' {
            Add-PoshifyFavorite -Name 'agnost' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Get-PoshifyFavorite | Should -BeNullOrEmpty
        }

        It 'accepts themes that are not installed, with a warning' {
            Add-PoshifyFavorite -Name 'night-owl' -WarningVariable warnings -WarningAction SilentlyContinue
            Get-PoshifyFavorite | Should -Be 'night-owl'
            "$warnings" | Should -Match 'not installed'
        }

        It 'marks favorite themes' {
            Add-PoshifyFavorite -Name 'atomic'
            (Get-PoshifyTheme | Where-Object Favorite).Name | Should -Be 'atomic'
        }

        It 'removes favorites' {
            Add-PoshifyFavorite -Name 'agnoster'
            Add-PoshifyFavorite -Name 'atomic'
            Remove-PoshifyFavorite -Name 'agnoster'
            Get-PoshifyFavorite | Should -Be 'atomic'

            Remove-PoshifyFavorite -Name 'agnoster' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'not in favorites'
        }
    }

    Context 'Get-PoshifyRandomTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'atomic.omp.json', 'paradox.omp.json'
        }

        It 'never picks the current theme when there is another choice' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            1..20 | ForEach-Object { (Get-PoshifyRandomTheme).Name } | Should -Not -Contain 'agnoster'
        }

        It 'picks only from favorites that are installed' {
            Add-PoshifyFavorite -Name 'paradox'
            Add-PoshifyFavorite -Name 'night-owl' -WarningAction SilentlyContinue
            1..10 | ForEach-Object { (Get-PoshifyRandomTheme -FromFavorites).Name } | Should -Be (@('paradox') * 10)
        }

        It 'errors when there are no favorites' {
            Get-PoshifyRandomTheme -FromFavorites -ErrorVariable err -ErrorAction SilentlyContinue | Should -BeNullOrEmpty
            "$err" | Should -Match 'favorite'
        }

        It 'does not change the theme by itself' {
            Get-PoshifyRandomTheme | Out-Null
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'can be piped into Set-PoshifyTheme' {
            $theme = Get-PoshifyRandomTheme
            $theme | Set-PoshifyTheme -NoApply
            (Get-PoshifyCurrentTheme).Name | Should -Be $theme.Name
        }
    }

    Context 'Show-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            Mock Invoke-OhMyPosh -ModuleName Poshify { "oh-my-posh $ArgumentList" }
        }

        It 'renders a preview with oh-my-posh without changing the theme' {
            $output = Show-PoshifyTheme -Name 'agnoster'
            $output[0] | Should -Be '== agnoster =='
            $output[1] | Should -BeLike 'oh-my-posh print preview --config *agnoster.omp.json'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'accepts themes from the pipeline' {
            (Get-PoshifyTheme | Show-PoshifyTheme)[0] | Should -Be '== agnoster =='
        }
    }

    Context 'Module surface' {
        It 'exports every command listed in the manifest' {
            $manifest = Import-PowerShellDataFile (Join-Path $PSScriptRoot '../Poshify/Poshify.psd1')
            $exported = (Get-Command -Module Poshify).Name
            foreach ($name in @($manifest.FunctionsToExport) + @($manifest.AliasesToExport)) {
                $exported | Should -Contain $name
            }
        }
    }

    Context 'Profiles for both PowerShell editions' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            $script:desktopProfile = Join-Path $TestDrive 'Documents/WindowsPowerShell/profile.ps1'
            Mock Get-PoshifyProfileTarget -ModuleName Poshify {
                [PSCustomObject]@{ Edition = 'Core'; Path = (Join-Path $TestDrive 'Documents/PowerShell/profile.ps1'); IsCurrent = $true }
                [PSCustomObject]@{ Edition = 'Desktop'; Path = (Join-Path $TestDrive 'Documents/WindowsPowerShell/profile.ps1'); IsCurrent = $false }
            }
        }

        It 'sets up the other edition too when it can run scripts' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match '# >>> poshify >>>'
            Get-Content -LiteralPath $script:desktopProfile -Raw | Should -Match '# >>> poshify >>>'
        }

        It 'does not create a profile for an edition that cannot run scripts' {
            Mock Get-PoshifyExecutionPolicy -ModuleName Poshify -ParameterFilter { $Edition -eq 'Desktop' } { 'Restricted' }
            Set-PoshifyTheme -Name 'agnoster' -NoApply -WarningVariable warnings
            $script:desktopProfile | Should -Not -Exist
            $warnings | Should -BeNullOrEmpty
        }

        It 'updates an existing profile it cannot run and explains how to allow it' {
            New-Item -ItemType Directory -Path (Split-Path $script:desktopProfile) -Force | Out-Null
            Set-Content -LiteralPath $script:desktopProfile -Value 'Import-Module posh-git'
            Mock Get-PoshifyExecutionPolicy -ModuleName Poshify -ParameterFilter { $Edition -eq 'Desktop' } { 'Restricted' }

            Set-PoshifyTheme -Name 'agnoster' -NoApply -WarningVariable warnings -WarningAction SilentlyContinue

            Get-Content -LiteralPath $script:desktopProfile -Raw | Should -Match '# >>> poshify >>>'
            "$warnings" | Should -Match 'Windows PowerShell can''t run your profile because its execution policy is Restricted'
            "$warnings" | Should -Match 'Set-ExecutionPolicy -Scope CurrentUser RemoteSigned'
        }

        It 'warns when the current edition cannot run scripts' {
            Mock Get-PoshifyExecutionPolicy -ModuleName Poshify -ParameterFilter { $Edition -eq 'Core' } { 'AllSigned' }
            Set-PoshifyTheme -Name 'agnoster' -NoApply -WarningVariable warnings -WarningAction SilentlyContinue
            $script:profilePath | Should -Exist
            "$warnings" | Should -Match 'PowerShell 7 can''t run your profile'
        }

        It 'only checks the execution policy when a profile changes' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Should -Invoke Get-PoshifyExecutionPolicy -ModuleName Poshify -Times 2 -Exactly
        }

        It 'resets both profiles' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Reset-PoshifyTheme
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Not -Match 'poshify'
            Get-Content -LiteralPath $script:desktopProfile -Raw | Should -Not -Match 'poshify'
        }
    }

    Context 'Themes that are only available online' {
        BeforeEach {
            Mock Get-PoshifyOnlineThemeList -ModuleName Poshify {
                [PSCustomObject]@{ PSTypeName = 'Poshify.OnlineTheme'; Name = 'atomic'; FileName = 'atomic.omp.json'; DownloadUrl = 'https://example.test/atomic.omp.json'; Sha = 'x' }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{}' }
            Mock Invoke-OhMyPosh -ModuleName Poshify { $global:PoshifyTestPreviewPath = $ArgumentList[-1]; 'preview' }
        }

        AfterEach {
            Remove-Variable -Name PoshifyTestPreviewPath -Scope Global -ErrorAction SilentlyContinue
        }

        It 'Set-PoshifyTheme downloads an exact online match first' {
            Set-PoshifyTheme -Name 'atomic' -NoApply
            Join-Path $script:home_ 'atomic.omp.json' | Should -Exist
            (Get-PoshifyCurrentTheme).Name | Should -Be 'atomic'
        }

        It 'Set-PoshifyTheme does not download partial online matches' {
            Set-PoshifyTheme -Name 'atom' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'not found locally or online'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly
        }

        It 'Set-PoshifyTheme -WhatIf downloads nothing' {
            Set-PoshifyTheme -Name 'atomic' -WhatIf
            Join-Path $script:home_ 'atomic.omp.json' | Should -Not -Exist
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'Show-PoshifyTheme previews from a temporary download' {
            $output = Show-PoshifyTheme -Name 'atomic'
            $output[0] | Should -Be '== atomic (not installed) =='
            $global:PoshifyTestPreviewPath | Should -BeLike '*poshify-preview-*atomic.omp.json'
            $global:PoshifyTestPreviewPath | Should -Not -Exist
            Join-Path $script:home_ 'atomic.omp.json' | Should -Not -Exist
        }
    }

    Context 'Windows Terminal font' -Skip:($PSVersionTable.PSEdition -ne 'Core') {
        BeforeEach {
            $script:settings = Join-Path $TestDrive 'settings.json'
        }

        It 'sets the default font and keeps everything else' {
            Set-Content -LiteralPath $script:settings -Value '{
                "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "profiles": {
                    "defaults": { "font": { "face": "Cascadia Mono", "size": 11 }, "opacity": 90 },
                    "list": [ { "name": "Windows PowerShell", "hidden": false } ]
                },
                "schemes": [],
                "actions": [ { "command": "paste", "keys": "ctrl+v" } ]
            }'

            InModuleScope Poshify -Parameters @{ Path = $script:settings } {
                param($Path)
                Get-PoshifyTerminalFont -Path $Path | Should -Be 'Cascadia Mono'
                Write-PoshifyTerminalFont -Path $Path -Face 'MesloLGM Nerd Font' | Should -BeTrue
                Get-PoshifyTerminalFont -Path $Path | Should -Be 'MesloLGM Nerd Font'
            }

            $result = Get-Content -LiteralPath $script:settings -Raw | ConvertFrom-Json
            $result.profiles.defaults.font.size | Should -Be 11
            $result.profiles.defaults.opacity | Should -Be 90
            $result.profiles.list[0].name | Should -Be 'Windows PowerShell'
            $result.actions[0].keys | Should -Be 'ctrl+v'
            "$($script:settings).poshify-backup" | Should -Exist
            (Get-Content -LiteralPath "$($script:settings).poshify-backup" -Raw) | Should -Match 'Cascadia Mono'
        }

        It 'adds the font setting when there is none' {
            Set-Content -LiteralPath $script:settings -Value '{ "profiles": { "list": [] } }'
            InModuleScope Poshify -Parameters @{ Path = $script:settings } {
                param($Path)
                Get-PoshifyTerminalFont -Path $Path | Should -Be 'Cascadia Mono'
                Write-PoshifyTerminalFont -Path $Path -Face 'MesloLGM Nerd Font' | Should -BeTrue
                Get-PoshifyTerminalFont -Path $Path | Should -Be 'MesloLGM Nerd Font'
            }
        }

        It 'leaves settings with comments alone' {
            $original = "{`n  // my settings`n  `"profiles`": { `"defaults`": {} }`n}"
            Set-Content -LiteralPath $script:settings -Value $original -NoNewline
            InModuleScope Poshify -Parameters @{ Path = $script:settings } {
                param($Path)
                Write-PoshifyTerminalFont -Path $Path -Face 'MesloLGM Nerd Font' -WarningAction SilentlyContinue | Should -BeFalse
            }
            Get-Content -LiteralPath $script:settings -Raw | Should -BeExactly $original
        }

        It 'warns about profiles that override the font' {
            Set-Content -LiteralPath $script:settings -Value '{ "profiles": { "defaults": {}, "list": [ { "name": "Ubuntu", "font": { "face": "Consolas" } } ] } }'
            InModuleScope Poshify -Parameters @{ Path = $script:settings } {
                param($Path)
                Write-PoshifyTerminalFont -Path $Path -Face 'MesloLGM Nerd Font' -WarningVariable warnings -WarningAction SilentlyContinue | Out-Null
                "$warnings" | Should -Match 'Ubuntu'
            }
        }
    }

    Context 'Initialize-Poshify' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'jandedobbeleer.omp.json'
            $global:PoshifyTestOutput = [System.Collections.Generic.List[string]]::new()
            Mock Write-Host -ModuleName Poshify { $global:PoshifyTestOutput.Add("$Object") }
            Mock Get-PoshifyNerdFont -ModuleName Poshify { 'MesloLGM Nerd Font' }
            Mock Get-PoshifyTerminalSettingsPath -ModuleName Poshify { }
            Mock Invoke-OhMyPosh -ModuleName Poshify { if ($ArgumentList[0] -eq 'version') { 'v-test' } }
            Mock Invoke-PoshifyInstaller -ModuleName Poshify { }
            Mock Sync-PoshifySessionPath -ModuleName Poshify { }
        }

        AfterEach {
            Remove-Variable -Name PoshifyTestOutput, PoshifyTestCalls -Scope Global -ErrorAction SilentlyContinue
        }

        It 'sets the requested theme and applies it to the session' {
            Initialize-Poshify -Theme 'agnoster' -Force
            (Get-PoshifyCurrentTheme).Name | Should -Be 'agnoster'
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match '# >>> poshify >>>'
            $global:PoshifyTestOutput -join "`n" | Should -Match 'Default theme: ''agnoster'''
            Should -Invoke Invoke-PoshifyInitScript -ModuleName Poshify -Times 1 -Exactly
        }


        It 'uses the oh-my-posh default theme when unattended' {
            Initialize-Poshify -Force
            (Get-PoshifyCurrentTheme).Name | Should -Be 'jandedobbeleer'
        }

        It 'keeps the current theme when run again' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Initialize-Poshify -Force
            (Get-PoshifyCurrentTheme).Name | Should -Be 'agnoster'
        }

        It 'installs oh-my-posh when it is missing' {
            $global:PoshifyTestCalls = 0
            Mock Get-OhMyPoshCommand -ModuleName Poshify {
                $global:PoshifyTestCalls++
                if ($global:PoshifyTestCalls -gt 1) { [PSCustomObject]@{ Name = 'oh-my-posh' } }
            }
            Mock Get-PoshifyOhMyPoshInstaller -ModuleName Poshify { [PSCustomObject]@{ Description = 'test installer'; FilePath = 'x'; ArgumentList = @() } }

            Initialize-Poshify -Theme 'agnoster' -Force

            Should -Invoke Invoke-PoshifyInstaller -ModuleName Poshify -Times 1 -Exactly
            Should -Invoke Sync-PoshifySessionPath -ModuleName Poshify -Times 1 -Exactly
            (Get-PoshifyCurrentTheme).Name | Should -Be 'agnoster'
        }

        It 'stops with guidance when oh-my-posh cannot be installed' {
            Mock Get-OhMyPoshCommand -ModuleName Poshify { }
            Mock Get-PoshifyOhMyPoshInstaller -ModuleName Poshify { }

            Initialize-Poshify -Theme 'agnoster' -Force

            $global:PoshifyTestOutput -join "`n" | Should -Match 'ohmyposh.dev'
            Get-PoshifyCurrentTheme | Should -BeNullOrEmpty
        }

        It 'installs a Nerd Font when none is present' {
            $global:PoshifyTestCalls = 0
            Mock Get-PoshifyNerdFont -ModuleName Poshify {
                $global:PoshifyTestCalls++
                if ($global:PoshifyTestCalls -gt 1) { 'MesloLGM Nerd Font' }
            }

            Initialize-Poshify -Theme 'agnoster' -Force

            Should -Invoke Invoke-OhMyPosh -ModuleName Poshify -Times 1 -Exactly -ParameterFilter { $ArgumentList -contains 'font' -and $ArgumentList -contains 'Meslo' }
        }

        It 'skips fonts with -SkipFont' {
            Initialize-Poshify -Theme 'agnoster' -Force -SkipFont
            Should -Invoke Get-PoshifyNerdFont -ModuleName Poshify -Times 0 -Exactly
        }

        It 'switches Windows Terminal to the Nerd Font' {
            Mock Get-PoshifyTerminalSettingsPath -ModuleName Poshify { 'C:\fake\settings.json' }
            Mock Get-PoshifyTerminalFont -ModuleName Poshify { 'Cascadia Mono' }
            Mock Write-PoshifyTerminalFont -ModuleName Poshify { $true }

            Initialize-Poshify -Theme 'agnoster' -Force

            Should -Invoke Write-PoshifyTerminalFont -ModuleName Poshify -Times 1 -Exactly -ParameterFilter { $Face -eq 'MesloLGM Nerd Font' }
        }

        It 'leaves a Windows Terminal that already uses a Nerd Font alone' {
            Mock Get-PoshifyTerminalSettingsPath -ModuleName Poshify { 'C:\fake\settings.json' }
            Mock Get-PoshifyTerminalFont -ModuleName Poshify { 'FiraCode Nerd Font' }
            Mock Write-PoshifyTerminalFont -ModuleName Poshify { $true }

            Initialize-Poshify -Theme 'agnoster' -Force

            Should -Invoke Write-PoshifyTerminalFont -ModuleName Poshify -Times 0 -Exactly
        }

        It 'explains a blocking execution policy without changing it' {
            Mock Get-PoshifyExecutionPolicy -ModuleName Poshify { 'Restricted' }
            Initialize-Poshify -Theme 'agnoster' -Force -WarningAction SilentlyContinue
            $global:PoshifyTestOutput -join "`n" | Should -Match 'Set-ExecutionPolicy -Scope CurrentUser RemoteSigned'
        }

        It 'changes nothing with -WhatIf' {
            Mock Get-PoshifyNerdFont -ModuleName Poshify { }
            Mock Get-PoshifyTerminalSettingsPath -ModuleName Poshify { 'C:\fake\settings.json' }
            Mock Get-PoshifyTerminalFont -ModuleName Poshify { 'Cascadia Mono' }
            Mock Write-PoshifyTerminalFont -ModuleName Poshify { $true }

            Initialize-Poshify -Theme 'agnoster' -WhatIf

            Should -Invoke Invoke-OhMyPosh -ModuleName Poshify -Times 0 -Exactly -ParameterFilter { $ArgumentList -contains 'font' }
            Should -Invoke Write-PoshifyTerminalFont -ModuleName Poshify -Times 0 -Exactly
            $script:profilePath | Should -Not -Exist
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'is available as "Poshify setup"' {
            Mock Initialize-Poshify -ModuleName Poshify { }
            Poshify setup
            Should -Invoke Initialize-Poshify -ModuleName Poshify -Times 1 -Exactly
        }
    }

    Context 'Folder theme resolution' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'atomic.omp.json', 'dracula.omp.yaml'
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            $script:project = Join-Path $TestDrive 'projects/app'
            $script:nested = Join-Path $script:project 'src/lib'
            New-Item -ItemType Directory -Path $script:nested -Force | Out-Null

            function script:Resolve-Test {
                param([string]$Path)
                InModuleScope Poshify -Parameters @{ Path = $Path; PoshifyHome = $script:home_ } {
                    param($Path, $PoshifyHome)
                    Resolve-PoshifyLocationTheme -Path $Path -PoshifyHome $PoshifyHome
                }
            }
        }

        It 'returns nothing when no folder file applies' {
            Resolve-Test -Path $script:nested | Should -BeNullOrEmpty
        }

        It 'finds theme names in Poshify and oh-my-posh theme folders, in any format' {
            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value 'dracula'
            (Resolve-Test -Path $script:nested).Path | Should -Be (Join-Path $script:home_ 'dracula.omp.yaml')

            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value 'agnoster'
            $result = Resolve-Test -Path $script:nested
            $result.Path | Should -Be (Join-Path $script:bundled 'agnoster.omp.json')
            $result.Status | Should -Be 'Active'
        }

        It 'uses the nearest folder file' {
            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value 'atomic'
            Set-Content -LiteralPath (Join-Path $script:project 'src/.poshify') -Value 'dracula'
            (Resolve-Test -Path $script:nested).Value | Should -Be 'dracula'
            (Resolve-Test -Path $script:project).Value | Should -Be 'atomic'
        }

        It 'reads .ompconfig files, preferring .poshify in the same folder' {
            Set-Content -LiteralPath (Join-Path $script:project '.ompconfig') -Value 'atomic'
            (Resolve-Test -Path $script:nested).Value | Should -Be 'atomic'

            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value 'dracula'
            (Resolve-Test -Path $script:nested).Value | Should -Be 'dracula'
        }

        It 'skips comments and blank lines' {
            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value '# project theme', '', '  atomic  '
            (Resolve-Test -Path $script:project).Value | Should -Be 'atomic'
        }

        It 'ignores folders named .poshify' {
            New-Item -ItemType Directory -Path (Join-Path $script:project '.poshify') | Out-Null
            Resolve-Test -Path $script:project | Should -BeNullOrEmpty
        }

        It 'reports themes that are not installed' {
            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value 'night-owl'
            $result = Resolve-Test -Path $script:project
            $result.Status | Should -Be 'NotFound'
            $result.Path | Should -BeNullOrEmpty
            $result.Message | Should -Match 'Poshify theme install night-owl'
        }

        It 'requires trust for theme files outside the theme folders, tied to their content' {
            $themeFile = Join-Path $script:project 'mine.omp.json'
            Set-Content -LiteralPath $themeFile -Value '{}'
            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value 'mine.omp.json'

            $result = Resolve-Test -Path $script:nested
            $result.Status | Should -Be 'Untrusted'
            $result.Path | Should -BeNullOrEmpty
            $result.File | Should -Be $themeFile

            InModuleScope Poshify -Parameters @{ File = $themeFile } { param($File) Add-PoshifyTrust -File $File }
            (Resolve-Test -Path $script:nested).Path | Should -Be $themeFile

            Set-Content -LiteralPath $themeFile -Value '{ "changed": true }'
            (Resolve-Test -Path $script:nested).Status | Should -Be 'Untrusted'
        }

        It 'trusts paths that point into the theme folders' {
            Set-Content -LiteralPath (Join-Path $script:project '.poshify') -Value (Join-Path $script:home_ 'atomic.omp.json')
            (Resolve-Test -Path $script:project).Status | Should -Be 'Active'
        }
    }

    Context 'Default theme selection' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'atomic.omp.json', 'paradox.omp.json'

            function script:Select-Test {
                InModuleScope Poshify -Parameters @{ PoshifyHome = $script:home_ } {
                    param($PoshifyHome)
                    Select-PoshifyDefaultThemeFile -PoshifyHome $PoshifyHome
                }
            }
        }

        It 'returns nothing without a selection' {
            Select-Test | Should -BeNullOrEmpty
        }

        It 'returns the selected theme file' {
            Set-PoshifyTheme -Name 'atomic' -NoApply
            Select-Test | Should -Be (Join-Path $script:bundled 'atomic.omp.json')
        }

        It 'Set-PoshifyTheme -Random picks from all themes' {
            Set-PoshifyTheme -Random -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be 'random'
            $picks = 1..30 | ForEach-Object { Split-Path -Leaf (Select-Test) } | Sort-Object -Unique
            $picks.Count | Should -BeGreaterThan 1
        }

        It 'Set-PoshifyTheme -Random -FromFavorites picks only favorites' {
            Add-PoshifyFavorite -Name 'paradox'
            Set-PoshifyTheme -Random -FromFavorites -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be 'random:favorites'
            1..10 | ForEach-Object { Split-Path -Leaf (Select-Test) } | Sort-Object -Unique | Should -Be 'paradox.omp.json'
        }

        It 'Set-PoshifyTheme -Random -FromFavorites needs favorites' {
            Set-PoshifyTheme -Random -FromFavorites -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'favorite'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }
    }

    Context 'Folder theme commands' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'atomic.omp.json'
            $script:project = Join-Path $TestDrive 'projects/app'
            New-Item -ItemType Directory -Path (Join-Path $script:project 'src') -Force | Out-Null
            $script:marker = Join-Path $script:project '.poshify'
        }

        It 'writes a .poshify file with the exact theme name and sets up the profile' {
            Set-PoshifyFolderTheme -Name 'atom' -Path $script:project
            (Get-Content -LiteralPath $script:marker).Trim() | Should -Be 'atomic'
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match '# >>> poshify >>>'
            Join-Path $script:home_ 'init.ps1' | Should -Exist
        }

        It 'downloads a theme that is only available online' {
            Mock Get-PoshifyOnlineThemeList -ModuleName Poshify {
                [PSCustomObject]@{ PSTypeName = 'Poshify.OnlineTheme'; Name = 'night-owl'; FileName = 'night-owl.omp.json'; DownloadUrl = 'https://example.test/night-owl.omp.json'; Sha = 'x' }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{}' }

            Set-PoshifyFolderTheme -Name 'night-owl' -Path $script:project
            Join-Path $script:home_ 'night-owl.omp.json' | Should -Exist
            (Get-PoshifyFolderTheme -Path $script:project).Status | Should -Be 'Active'
        }

        It 'stores a project theme file relative to the folder and trusts it' {
            $themeFile = Join-Path $script:project 'src/project.omp.json'
            Set-Content -LiteralPath $themeFile -Value '{}'

            Set-PoshifyFolderTheme -ThemePath $themeFile -Path $script:project

            (Get-Content -LiteralPath $script:marker).Trim() | Should -Be ([IO.Path]::Combine('src', 'project.omp.json'))
            $folderTheme = Get-PoshifyFolderTheme -Path (Join-Path $script:project 'src')
            $folderTheme.Status | Should -Be 'Active'
            $folderTheme.Theme | Should -Be 'project'
        }

        It 'shows untrusted folder themes until they are approved' {
            Set-Content -LiteralPath (Join-Path $script:project 'evil.omp.json') -Value '{}'
            Set-Content -LiteralPath $script:marker -Value 'evil.omp.json'

            $folderTheme = Get-PoshifyFolderTheme -Path $script:project
            $folderTheme.Status | Should -Be 'Untrusted'
            $folderTheme.Message | Should -Match 'Poshify folder trust'

            Approve-PoshifyFolderTheme -Path $script:project -WhatIf
            (Get-PoshifyFolderTheme -Path $script:project).Status | Should -Be 'Untrusted'

            Approve-PoshifyFolderTheme -Path $script:project
            (Get-PoshifyFolderTheme -Path $script:project).Status | Should -Be 'Active'
        }

        It 'clears .poshify and .ompconfig files and mentions inherited themes' {
            Set-Content -LiteralPath (Join-Path $TestDrive 'projects/.poshify') -Value 'agnoster'
            Set-Content -LiteralPath $script:marker -Value 'atomic'
            Set-Content -LiteralPath (Join-Path $script:project '.ompconfig') -Value 'atomic'

            Clear-PoshifyFolderTheme -Path $script:project -WarningVariable warnings -WarningAction SilentlyContinue

            $script:marker | Should -Not -Exist
            Join-Path $script:project '.ompconfig' | Should -Not -Exist
            "$warnings" | Should -Match 'still gets a theme'
            (Get-PoshifyFolderTheme -Path $script:project).Theme | Should -Be 'agnoster'
        }

        It 'changes nothing with -WhatIf' {
            Set-PoshifyFolderTheme -Name 'atomic' -Path $script:project -WhatIf
            $script:marker | Should -Not -Exist

            Set-Content -LiteralPath $script:marker -Value 'atomic'
            Clear-PoshifyFolderTheme -Path $script:project -WhatIf
            $script:marker | Should -Exist
        }

        It 'Get-PoshifyCurrentTheme reports the folder theme and why' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Set-PoshifyFolderTheme -Name 'atomic' -Path $script:project

            $here = Get-PoshifyCurrentTheme -Path (Join-Path $script:project 'src')
            $here.Name | Should -Be 'atomic'
            $here.SelectedBy | Should -Match ([regex]::Escape($script:marker))

            $elsewhere = Get-PoshifyCurrentTheme -Path $TestDrive
            $elsewhere.Name | Should -Be 'agnoster'
            $elsewhere.SelectedBy | Should -Be 'Default'
        }

        It 'is available as "Poshify folder ..."' {
            Push-Location -LiteralPath $script:project
            try {
                Poshify folder set atomic 6>$null
                (Get-Content -LiteralPath $script:marker).Trim() | Should -Be 'atomic'
                Poshify folder clear 3>$null
                $script:marker | Should -Not -Exist
            }
            finally {
                Pop-Location
            }
        }
    }

    Context 'Generated init script' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'atomic.omp.json'
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            $script:projectA = Join-Path $TestDrive 'work/a'
            $script:projectB = Join-Path $TestDrive 'work/b'
            New-Item -ItemType Directory -Path (Join-Path $script:projectA 'sub'), $script:projectB -Force | Out-Null
            Set-Content -LiteralPath (Join-Path $script:projectA '.poshify') -Value 'atomic'
            Set-Content -LiteralPath (Join-Path $script:projectB 'evil.omp.json') -Value '{}'
            Set-Content -LiteralPath (Join-Path $script:projectB '.poshify') -Value 'evil.omp.json'

            # A fake oh-my-posh whose init script records the config and installs a recognisable prompt
            $script:bin = Join-Path $TestDrive 'bin'
            New-Item -ItemType Directory -Path $script:bin -Force | Out-Null
            if ($PSVersionTable.PSEdition -eq 'Desktop' -or $IsWindows) {
                Set-Content -LiteralPath (Join-Path $script:bin 'oh-my-posh.cmd') -Encoding ASCII -Value @(
                    '@echo off'
                    'if "%1"=="init" echo $global:PoshifyFakeInits += ,''%~4''; function global:prompt { ''OMP:%~n4 '' }'
                )
            }
            else {
                $fake = Join-Path $script:bin 'oh-my-posh'
                Set-Content -LiteralPath $fake -Value @(
                    '#!/bin/sh'
                    'if [ "$1" = "init" ]; then name=$(basename "$4" .json); echo "\$global:PoshifyFakeInits += ,''$4''; function global:prompt { ''OMP:$name '' }"; fi'
                )
                chmod +x $fake
            }

            Set-PoshifyTheme -Name 'agnoster' -NoApply
        }

        It 'switches themes by folder, warns once about untrusted themes and keeps the exit code' {
            $initScript = Join-Path $script:home_ 'init.ps1'
            $initScript | Should -Exist
            $script = @"
`$env:PATH = '$($script:bin)' + [IO.Path]::PathSeparator + `$env:PATH
`$env:POSH_THEMES_PATH = '$($script:bundled)'
. '$initScript'
'start=' + (prompt)
Set-Location -LiteralPath '$($script:projectA)'; 'a=' + (prompt)
Set-Location -LiteralPath '$(Join-Path $script:projectA 'sub')'; 'sub=' + (prompt)
Set-Location -LiteralPath '$($script:projectB)'; 'b=' + (prompt)
Set-Location -LiteralPath '$($script:projectA)'; 'a2=' + (prompt)
Set-Location -LiteralPath '$($script:projectB)'; 'b2=' + (prompt)
`$global:LASTEXITCODE = 7; `$null = prompt; 'exit=' + `$global:LASTEXITCODE
'status=' + (`$global:NVS_ORIGINAL_LASTEXECUTIONSTATUS -is [bool])
'inits=' + `$global:PoshifyFakeInits.Count
"@
            $exe = (Get-Process -Id $PID).Path
            $output = & $exe -NoProfile -NonInteractive -Command $script 2>&1 | ForEach-Object { "$_".Trim() }

            $output | Should -Contain 'start=OMP:agnoster.omp'
            $output | Should -Contain 'a=OMP:atomic.omp'
            $output | Should -Contain 'sub=OMP:atomic.omp'
            $output | Should -Contain 'b=OMP:agnoster.omp'
            $output | Should -Contain 'a2=OMP:atomic.omp'
            $output | Should -Contain 'exit=7'
            $output | Should -Contain 'status=True'
            # agnoster, atomic, agnoster, atomic, agnoster: no re-init inside the same theme
            $output | Should -Contain 'inits=5'
            @($output | Where-Object { $_ -match "isn't trusted" }).Count | Should -Be 1
        }

        It 'does nothing when oh-my-posh is not installed' {
            $initScript = Join-Path $script:home_ 'init.ps1'
            $exe = (Get-Process -Id $PID).Path
            $script = "`$env:PATH = ''; . '$initScript'; 'loaded=' + [bool]`$global:_poshifyUpdate"
            $output = & $exe -NoProfile -NonInteractive -Command $script 2>&1 | ForEach-Object { "$_".Trim() }
            $output | Should -Contain 'loaded=False'
        }

        It 'is rewritten only when its content changes' {
            $initScript = Join-Path $script:home_ 'init.ps1'
            (Get-Item -LiteralPath $initScript).LastWriteTime = [datetime]'2000-01-01'
            Set-PoshifyTheme -Name 'atomic' -NoApply
            (Get-Item -LiteralPath $initScript).LastWriteTime | Should -Be ([datetime]'2000-01-01')
        }

        It 'Reset removes it' {
            Reset-PoshifyTheme
            Join-Path $script:home_ 'init.ps1' | Should -Not -Exist
        }
    }
}
