BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '../Poshify/Poshify.psd1') -Force

    function New-ThemeFile {
        param([string]$Directory, [string[]]$FileName)
        New-Item -ItemType Directory -Path $Directory -Force | Out-Null
        foreach ($file in $FileName) {
            Set-Content -LiteralPath (Join-Path $Directory $file) -Value '{}'
        }
    }
}

AfterAll {
    Remove-Module Poshify -Force -ErrorAction SilentlyContinue
}

Describe 'Poshify' {
    BeforeEach {
        $script:home_ = Join-Path $TestDrive 'home/.poshthemes'
        $script:bundled = Join-Path $TestDrive 'oh-my-posh/themes'
        $script:profilePath = Join-Path $TestDrive 'Documents/PowerShell/profile.ps1'
        Remove-Item -Path (Join-Path $TestDrive '*') -Recurse -Force -ErrorAction SilentlyContinue

        $script:savedThemesPath = $env:POSH_THEMES_PATH
        $env:POSH_THEMES_PATH = $script:bundled

        InModuleScope Poshify -Parameters @{ Path = $script:home_ } {
            param($Path)
            $script:PoshifyHome = $Path
        }
        Mock Get-PoshifyProfilePath -ModuleName Poshify { Join-Path $TestDrive 'Documents/PowerShell/profile.ps1' }
        Mock Get-OhMyPoshCommand -ModuleName Poshify { [PSCustomObject]@{ Name = 'oh-my-posh' } }
    }

    AfterEach {
        $env:POSH_THEMES_PATH = $script:savedThemesPath
    }

    Context 'Merge-PoshifyProfileBlock' {
        It 'appends the block after existing content' {
            InModuleScope Poshify {
                $result = Merge-PoshifyProfileBlock -Content "Import-Module Terminal-Icons`n"
                $result | Should -Match '^Import-Module Terminal-Icons\n\n# >>> poshify >>>\n'
                $result | Should -Match '# <<< poshify <<<\n$'
            }
        }

        It 'is idempotent' {
            InModuleScope Poshify {
                $once = Merge-PoshifyProfileBlock -Content "Import-Module Terminal-Icons`n"
                Merge-PoshifyProfileBlock -Content $once | Should -BeExactly $once
            }
        }

        It 'keeps the block where the user moved it and drops duplicates' {
            InModuleScope Poshify {
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                $content = "# top`n$block`n# middle`n$block`n# bottom`n"
                Merge-PoshifyProfileBlock -Content $content | Should -BeExactly "# top`n$block`n# middle`n# bottom`n"
            }
        }

        It 'replaces an outdated block in place' {
            InModuleScope Poshify {
                $content = "# top`n# >>> poshify >>>`nold stuff`n# <<< poshify <<<`n# bottom`n"
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                Merge-PoshifyProfileBlock -Content $content | Should -BeExactly "# top`n$block`n# bottom`n"
            }
        }

        It 'migrates complete and partially-removed blocks written by Poshify 1.0' {
            InModuleScope Poshify {
                $legacy = "# Poshify Theme - Generated by Poshify Module`n# Theme: agnoster`n# Generated on: 2025-01-01 10:00:00`n`noh-my-posh init pwsh --config `"C:\t\agnoster.omp.json`" | Invoke-Expression"
                # What the 1.0 cleanup regex left behind: the header line removed, the rest kept
                $leftover = "# Theme: atomic`n# Generated on: 2025-01-02 10:00:00`n`noh-my-posh init pwsh --config `"C:\t\atomic.omp.json`" | Invoke-Expression"
                $content = "Import-Module posh-git`n`n$leftover`n`n$legacy`n"

                $result = Merge-PoshifyProfileBlock -Content $content -Remove
                $result | Should -BeExactly "Import-Module posh-git`n"
            }
        }

        It 'only removes its own block and leaves other oh-my-posh setup intact' {
            InModuleScope Poshify {
                $foreign = '& ([ScriptBlock]::Create((oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json") -join "`n"))'
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                Merge-PoshifyProfileBlock -Content "$foreign`n`n$block`n" -Remove | Should -BeExactly "$foreign`n"
            }
        }

        It 'preserves CRLF line endings' {
            InModuleScope Poshify {
                $result = Merge-PoshifyProfileBlock -Content "Import-Module posh-git`r`n"
                ($result -replace "`r`n", '') | Should -Not -Match "`n"
            }
        }

        It 'generates a block that runs cleanly when no theme is selected' {
            InModuleScope Poshify {
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                { & ([scriptblock]::Create($block)) } | Should -Not -Throw
            }
        }
    }

    Context 'Get-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'custom.omp.yaml'
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.toml', 'readme.md'
        }

        It 'lists themes from Poshify and oh-my-posh, with downloads shadowing bundled themes' {
            $themes = Get-PoshifyTheme
            $themes.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic', 'custom')
            ($themes | Where-Object Name -eq 'agnoster').Source | Should -Be 'Poshify'
        }

        It 'prefers an exact name match over partial matches' {
            $result = @(Get-PoshifyTheme -Name 'agnoster')
            $result.Count | Should -Be 1
            $result[0].Name | Should -Be 'agnoster'
        }

        It 'falls back to substring and wildcard matching' {
            @(Get-PoshifyTheme -Name 'plus').Name | Should -Be 'agnosterplus'
            @(Get-PoshifyTheme -Name 'a*').Count | Should -Be 3
        }

        It 'writes an error when nothing matches' {
            Get-PoshifyTheme -Name 'nope' -ErrorVariable err -ErrorAction SilentlyContinue | Should -BeNullOrEmpty
            $err | Should -Not -BeNullOrEmpty
        }

        It 'tolerates a POSH_THEMES_PATH that does not exist' {
            $env:POSH_THEMES_PATH = Join-Path $TestDrive 'missing'
            { Get-PoshifyTheme -ErrorAction Stop } | Should -Not -Throw
            (Get-PoshifyTheme).Name | Should -Be @('agnoster', 'custom')
        }
    }

    Context 'Set-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.json'
        }

        It 'creates the profile and its directory when missing' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $script:profilePath | Should -Exist
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match '# >>> poshify >>>'
        }

        It 'records the selection and marks the theme as current' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be (Join-Path $script:bundled 'agnoster.omp.json')
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'agnoster'
        }

        It 'does not rewrite the profile when switching themes' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $before = Get-Content -LiteralPath $script:profilePath -Raw
            (Get-Item $script:profilePath).LastWriteTime = [datetime]'2000-01-01'

            Set-PoshifyTheme -Name 'atomic' -NoApply

            Get-Content -LiteralPath $script:profilePath -Raw | Should -BeExactly $before
            (Get-Item $script:profilePath).LastWriteTime | Should -Be ([datetime]'2000-01-01')
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'atomic'
        }

        It 'keeps existing profile content and encoding' {
            New-Item -ItemType Directory -Path (Split-Path $script:profilePath) -Force | Out-Null
            $original = "Write-Output 'héllo wörld'`r`n"
            [IO.File]::WriteAllText($script:profilePath, $original, (New-Object Text.UTF8Encoding($false)))

            Set-PoshifyTheme -Name 'agnoster' -NoApply

            $bytes = [IO.File]::ReadAllBytes($script:profilePath)
            $bytes[0] | Should -Not -Be 0xEF
            $text = [IO.File]::ReadAllText($script:profilePath)
            $text | Should -BeLike "$original`r`n# >>> poshify >>>*"
        }

        It 'refuses an ambiguous partial name instead of guessing' {
            Set-PoshifyTheme -Name 'agnost' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'accepts themes from the pipeline' {
            Get-PoshifyTheme -Name 'atomic' | Set-PoshifyTheme -NoApply
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'atomic'
        }

        It 'accepts a direct path' {
            $custom = Join-Path $TestDrive 'mine.omp.json'
            Set-Content -LiteralPath $custom -Value '{}'
            Set-PoshifyTheme -ThemePath $custom -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be $custom
        }

        It 'changes nothing with -WhatIf' {
            Set-PoshifyTheme -Name 'agnoster' -WhatIf
            $script:profilePath | Should -Not -Exist
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'fails when oh-my-posh is not installed' {
            Mock Get-OhMyPoshCommand -ModuleName Poshify { }
            Set-PoshifyTheme -Name 'agnoster' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'not installed'
            $script:profilePath | Should -Not -Exist
        }
    }

    Context 'Reset-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            New-Item -ItemType Directory -Path (Split-Path $script:profilePath) -Force | Out-Null
            Set-Content -LiteralPath $script:profilePath -Value 'Import-Module posh-git'
            Set-PoshifyTheme -Name 'agnoster' -NoApply
        }

        It 'removes the block and selection, keeping the rest of the profile' {
            Reset-PoshifyTheme
            (Get-Content -LiteralPath $script:profilePath -Raw).Trim() | Should -BeExactly 'Import-Module posh-git'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'warns about oh-my-posh setup it did not create' {
            Add-Content -LiteralPath $script:profilePath -Value 'oh-my-posh init pwsh | Invoke-Expression'
            Reset-PoshifyTheme -WarningVariable warnings -WarningAction SilentlyContinue
            "$warnings" | Should -Match 'outside Poshify'
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match 'oh-my-posh init pwsh'
        }

        It 'changes nothing with -WhatIf' {
            $before = Get-Content -LiteralPath $script:profilePath -Raw
            Reset-PoshifyTheme -WhatIf
            Get-Content -LiteralPath $script:profilePath -Raw | Should -BeExactly $before
        }
    }


    Context 'Find-PoshifyTheme' {
        BeforeEach {
            Mock Invoke-RestMethod -ModuleName Poshify {
                @(
                    [PSCustomObject]@{ name = 'agnoster.omp.json'; size = 2048; download_url = 'https://example.test/agnoster.omp.json'; sha = 'a1' }
                    [PSCustomObject]@{ name = 'agnosterplus.omp.json'; size = 2048; download_url = 'https://example.test/agnosterplus.omp.json'; sha = 'b2' }
                    [PSCustomObject]@{ name = 'atomic.omp.yaml'; size = 1024; download_url = 'https://example.test/atomic.omp.yaml'; sha = 'c3' }
                    [PSCustomObject]@{ name = 'schema.json'; size = 10; download_url = 'https://example.test/schema.json'; sha = 'd4' }
                )
            }
        }

        It 'returns only theme files' {
            (Find-PoshifyTheme).Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
        }

        It 'returns a single match' {
            $result = @(Find-PoshifyTheme -Name 'atomic')
            $result.Count | Should -Be 1
            $result[0].FileName | Should -Be 'atomic.omp.yaml'
            $result[0].Sha | Should -Be 'c3'
        }

        It 'reuses the cached list until -ForceRefresh' {
            Find-PoshifyTheme | Out-Null
            $cached = Find-PoshifyTheme
            Should -Invoke Invoke-RestMethod -ModuleName Poshify -Times 1 -Exactly
            $cached.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
            $cached[0].PSObject.TypeNames | Should -Contain 'Poshify.OnlineTheme'

            Find-PoshifyTheme -ForceRefresh | Out-Null
            Should -Invoke Invoke-RestMethod -ModuleName Poshify -Times 2 -Exactly
        }

        It 'refetches once the cache is older than an hour' {
            Find-PoshifyTheme | Out-Null
            $cacheFile = Join-Path $script:home_ '.cache/themes.json'
            $cache = Get-Content $cacheFile -Raw | ConvertFrom-Json
            $cache.CachedAt = [datetime]::UtcNow.AddHours(-2).ToString('o')
            $cache | ConvertTo-Json -Depth 3 | Set-Content $cacheFile

            Find-PoshifyTheme | Out-Null
            Should -Invoke Invoke-RestMethod -ModuleName Poshify -Times 2 -Exactly
        }

        It 'falls back to a stale cache when GitHub is unreachable' {
            Find-PoshifyTheme | Out-Null
            Mock Invoke-RestMethod -ModuleName Poshify { throw 'No such host is known' }

            $result = Find-PoshifyTheme -ForceRefresh -WarningVariable warnings -WarningAction SilentlyContinue
            $result.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
            "$warnings" | Should -Match 'cached'
        }

        It 'reports GitHub rate limiting clearly' {
            Mock Invoke-RestMethod -ModuleName Poshify { throw 'API rate limit exceeded for 1.2.3.4' }
            Find-PoshifyTheme -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'rate limit reached'
        }
    }

    Context 'Install-PoshifyTheme' {
        BeforeEach {
            Mock Get-PoshifyOnlineThemeList -ModuleName Poshify {
                foreach ($name in 'agnoster', 'agnosterplus', 'atomic') {
                    [PSCustomObject]@{ Name = $name; FileName = "$name.omp.json"; DownloadUrl = "https://example.test/$name.omp.json"; Sha = 'x' }
                }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{}' }
        }

        It 'downloads the exact match without prompting' {
            $theme = Install-PoshifyTheme -Name 'agnoster'
            $theme.Name | Should -Be 'agnoster'
            $theme.Source | Should -Be 'Poshify'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 1 -Exactly
        }

        It 'errors on an ambiguous name instead of prompting' {
            Install-PoshifyTheme -Name 'agnost' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly
        }

        It 'returns an existing local theme unless -Force is used' {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            (Install-PoshifyTheme -Name 'agnoster' -WarningAction SilentlyContinue).Source | Should -Be 'oh-my-posh'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly

            (Install-PoshifyTheme -Name 'agnoster' -Force).Source | Should -Be 'Poshify'
        }

        It 'is not fooled by a local theme that only contains the name' {
            New-ThemeFile -Directory $script:bundled -FileName 'agnosterplus.omp.json'
            (Install-PoshifyTheme -Name 'agnoster').Name | Should -Be 'agnoster'
        }

        It 'leaves no partial file when the download fails' {
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value 'partial'; throw 'connection reset' }
            Install-PoshifyTheme -Name 'atomic' -ErrorAction SilentlyContinue
            Get-ChildItem -LiteralPath $script:home_ | Should -BeNullOrEmpty
        }

        It 'queries GitHub once for piped themes' {
            [PSCustomObject]@{ Name = 'agnoster' }, [PSCustomObject]@{ Name = 'atomic' } | Install-PoshifyTheme
            Should -Invoke Get-PoshifyOnlineThemeList -ModuleName Poshify -Times 1 -Exactly
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 2 -Exactly
        }
    }

    Context 'Update-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'atomic.omp.json', 'retired.omp.json'
            New-ThemeFile -Directory $script:bundled -FileName 'bundled.omp.json'
            $script:upToDateSha = InModuleScope Poshify -Parameters @{ Path = (Join-Path $script:home_ 'agnoster.omp.json') } {
                param($Path)
                Get-PoshifyGitBlobSha -Path $Path
            }
            Mock Get-PoshifyOnlineThemeList -ModuleName Poshify -ParameterFilter { $ForceRefresh } {
                [PSCustomObject]@{ Name = 'agnoster'; FileName = 'agnoster.omp.json'; DownloadUrl = 'https://example.test/agnoster.omp.json'; Sha = $script:upToDateSha }
                [PSCustomObject]@{ Name = 'atomic'; FileName = 'atomic.omp.json'; DownloadUrl = 'https://example.test/atomic.omp.json'; Sha = 'changed' }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{"new": true}' }
        }

        It 'matches git blob hashes reported by GitHub' {
            # Well-known `git hash-object` result for "hello world\n"
            $file = Join-Path $TestDrive 'hello.txt'
            [IO.File]::WriteAllText($file, "hello world`n")
            InModuleScope Poshify -Parameters @{ Path = $file } {
                param($Path)
                Get-PoshifyGitBlobSha -Path $Path
            } | Should -Be '3b18e512dba79e4c8300dd08aeb37f8e728b8dad'
        }

        It 'downloads only themes that changed online' {
            $updated = @(Update-PoshifyTheme -All -WarningAction SilentlyContinue)
            $updated.Name | Should -Be 'atomic'
            Get-Content (Join-Path $script:home_ 'atomic.omp.json') -Raw | Should -Match 'new'
            Get-Content (Join-Path $script:home_ 'agnoster.omp.json') -Raw | Should -Not -Match 'new'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 1 -Exactly
        }

        It 'keeps themes that were removed upstream and warns' {
            Update-PoshifyTheme -Name 'retired' -WarningVariable warnings -WarningAction SilentlyContinue
            "$warnings" | Should -Match 'no longer in the oh-my-posh repository'
            Join-Path $script:home_ 'retired.omp.json' | Should -Exist
        }

        It 'only updates themes installed by Poshify' {
            Update-PoshifyTheme -Name 'bundled' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'installed by Poshify'
            Should -Invoke Get-PoshifyOnlineThemeList -ModuleName Poshify -Times 0 -Exactly
        }

        It 'changes nothing with -WhatIf' {
            Update-PoshifyTheme -Name 'atomic' -WhatIf
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly
        }
    }

    Context 'Remove-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'agnosterplus.omp.json'
            New-ThemeFile -Directory $script:bundled -FileName 'atomic.omp.json'
        }

        It 'removes a downloaded theme' {
            Remove-PoshifyTheme -Name 'agnoster'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Not -Exist
            Join-Path $script:home_ 'agnosterplus.omp.json' | Should -Exist
        }

        It 'requires the exact name' {
            Remove-PoshifyTheme -Name 'plus' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'exact theme name'
            Join-Path $script:home_ 'agnosterplus.omp.json' | Should -Exist
        }

        It 'refuses to remove themes bundled with oh-my-posh' {
            Remove-PoshifyTheme -Name 'atomic' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'bundled with oh-my-posh'
            Join-Path $script:bundled 'atomic.omp.json' | Should -Exist
        }

        It 'protects the current theme unless -Force is used' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Remove-PoshifyTheme -Name 'agnoster' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'current theme'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist

            Remove-PoshifyTheme -Name 'agnoster' -Force -WarningAction SilentlyContinue
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Not -Exist
        }

        It 'changes nothing with -WhatIf' {
            Remove-PoshifyTheme -Name 'agnoster' -WhatIf
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist
        }
    }

    Context 'Get-PoshifyCurrentTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            $script:custom = Join-Path $TestDrive 'mine.omp.json'
            Set-Content -LiteralPath $script:custom -Value '{}'
        }

        It 'returns nothing when no theme is selected' {
            Get-PoshifyCurrentTheme | Should -BeNullOrEmpty
        }

        It 'returns the selected theme' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $current = Get-PoshifyCurrentTheme
            $current.Name | Should -Be 'agnoster'
            $current.Current | Should -BeTrue
        }

        It 'reports themes set by path as custom' {
            Set-PoshifyTheme -ThemePath $script:custom -NoApply
            $current = Get-PoshifyCurrentTheme
            $current.Name | Should -Be 'mine'
            $current.Source | Should -Be 'Custom'
        }

        It 'warns when the selected file is gone' {
            Set-PoshifyTheme -ThemePath $script:custom -NoApply
            [IO.File]::Delete($script:custom)

            Get-PoshifyCurrentTheme -WarningVariable warnings -WarningAction SilentlyContinue | Should -BeNullOrEmpty
            "$warnings" | Should -Match 'no longer exists'
        }
    }

    Context 'Favorites' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.json'
        }

        It 'keeps a proper list when adding several favorites' {
            Add-PoshifyFavorite -Name 'agnoster'
            Add-PoshifyFavorite -Name 'atomic'
            Add-PoshifyFavorite -Name 'agnoster'

            Get-PoshifyFavorite | Should -Be @('agnoster', 'atomic')
        }

        It 'stores a single favorite as a JSON list' {
            Add-PoshifyFavorite -Name 'atomic'
            (Get-Content (Join-Path $script:home_ '.favorites.json') -Raw).Trim() | Should -Match '^\['
        }

        It 'stores the exact theme name for a unique partial match' {
            Add-PoshifyFavorite -Name 'plus'
            Get-PoshifyFavorite | Should -Be 'agnosterplus'
        }

        It 'rejects an ambiguous name' {
            Add-PoshifyFavorite -Name 'agnost' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Get-PoshifyFavorite | Should -BeNullOrEmpty
        }

        It 'accepts themes that are not installed, with a warning' {
            Add-PoshifyFavorite -Name 'night-owl' -WarningVariable warnings -WarningAction SilentlyContinue
            Get-PoshifyFavorite | Should -Be 'night-owl'
            "$warnings" | Should -Match 'not installed'
        }

        It 'marks favorite themes' {
            Add-PoshifyFavorite -Name 'atomic'
            (Get-PoshifyTheme | Where-Object Favorite).Name | Should -Be 'atomic'
        }

        It 'removes favorites' {
            Add-PoshifyFavorite -Name 'agnoster'
            Add-PoshifyFavorite -Name 'atomic'
            Remove-PoshifyFavorite -Name 'agnoster'
            Get-PoshifyFavorite | Should -Be 'atomic'

            Remove-PoshifyFavorite -Name 'agnoster' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'not in favorites'
        }
    }

    Context 'Get-PoshifyRandomTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'atomic.omp.json', 'paradox.omp.json'
        }

        It 'never picks the current theme when there is another choice' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            1..20 | ForEach-Object { (Get-PoshifyRandomTheme).Name } | Should -Not -Contain 'agnoster'
        }

        It 'picks only from favorites that are installed' {
            Add-PoshifyFavorite -Name 'paradox'
            Add-PoshifyFavorite -Name 'night-owl' -WarningAction SilentlyContinue
            1..10 | ForEach-Object { (Get-PoshifyRandomTheme -FromFavorites).Name } | Should -Be (@('paradox') * 10)
        }

        It 'errors when there are no favorites' {
            Get-PoshifyRandomTheme -FromFavorites -ErrorVariable err -ErrorAction SilentlyContinue | Should -BeNullOrEmpty
            "$err" | Should -Match 'favorite'
        }

        It 'does not change the theme by itself' {
            Get-PoshifyRandomTheme | Out-Null
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'can be piped into Set-PoshifyTheme' {
            $theme = Get-PoshifyRandomTheme
            $theme | Set-PoshifyTheme -NoApply
            (Get-PoshifyCurrentTheme).Name | Should -Be $theme.Name
        }
    }

    Context 'Show-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            Mock Invoke-OhMyPosh -ModuleName Poshify { "oh-my-posh $ArgumentList" }
        }

        It 'renders a preview with oh-my-posh without changing the theme' {
            $output = Show-PoshifyTheme -Name 'agnoster'
            $output[0] | Should -Be '== agnoster =='
            $output[1] | Should -BeLike 'oh-my-posh print preview --config *agnoster.omp.json'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'accepts themes from the pipeline' {
            (Get-PoshifyTheme | Show-PoshifyTheme)[0] | Should -Be '== agnoster =='
        }
    }

    Context 'Module surface' {
        It 'exports every command listed in the manifest' {
            $manifest = Import-PowerShellDataFile (Join-Path $PSScriptRoot '../Poshify/Poshify.psd1')
            $exported = (Get-Command -Module Poshify).Name
            foreach ($name in @($manifest.FunctionsToExport) + @($manifest.AliasesToExport)) {
                $exported | Should -Contain $name
            }
        }
    }
}
