BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '../Poshify/Poshify.psd1') -Force

    function New-ThemeFile {
        param([string]$Directory, [string[]]$FileName)
        New-Item -ItemType Directory -Path $Directory -Force | Out-Null
        foreach ($file in $FileName) {
            Set-Content -LiteralPath (Join-Path $Directory $file) -Value '{}'
        }
    }
}

AfterAll {
    Remove-Module Poshify -Force -ErrorAction SilentlyContinue
}

Describe 'Poshify' {
    BeforeEach {
        $script:home_ = Join-Path $TestDrive 'home/.poshthemes'
        $script:bundled = Join-Path $TestDrive 'oh-my-posh/themes'
        $script:profilePath = Join-Path $TestDrive 'Documents/PowerShell/profile.ps1'
        Remove-Item -Path (Join-Path $TestDrive '*') -Recurse -Force -ErrorAction SilentlyContinue

        $script:savedThemesPath = $env:POSH_THEMES_PATH
        $env:POSH_THEMES_PATH = $script:bundled

        InModuleScope Poshify -Parameters @{ Path = $script:home_ } {
            param($Path)
            $script:PoshifyHome = $Path
        }
        Mock Get-PoshifyProfilePath -ModuleName Poshify { Join-Path $TestDrive 'Documents/PowerShell/profile.ps1' }
        Mock Get-OhMyPoshCommand -ModuleName Poshify { [PSCustomObject]@{ Name = 'oh-my-posh' } }
    }

    AfterEach {
        $env:POSH_THEMES_PATH = $script:savedThemesPath
    }

    Context 'Merge-PoshifyProfileBlock' {
        It 'appends the block after existing content' {
            InModuleScope Poshify {
                $result = Merge-PoshifyProfileBlock -Content "Import-Module Terminal-Icons`n"
                $result | Should -Match '^Import-Module Terminal-Icons\n\n# >>> poshify >>>\n'
                $result | Should -Match '# <<< poshify <<<\n$'
            }
        }

        It 'is idempotent' {
            InModuleScope Poshify {
                $once = Merge-PoshifyProfileBlock -Content "Import-Module Terminal-Icons`n"
                Merge-PoshifyProfileBlock -Content $once | Should -BeExactly $once
            }
        }

        It 'keeps the block where the user moved it and drops duplicates' {
            InModuleScope Poshify {
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                $content = "# top`n$block`n# middle`n$block`n# bottom`n"
                Merge-PoshifyProfileBlock -Content $content | Should -BeExactly "# top`n$block`n# middle`n# bottom`n"
            }
        }

        It 'replaces an outdated block in place' {
            InModuleScope Poshify {
                $content = "# top`n# >>> poshify >>>`nold stuff`n# <<< poshify <<<`n# bottom`n"
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                Merge-PoshifyProfileBlock -Content $content | Should -BeExactly "# top`n$block`n# bottom`n"
            }
        }

        It 'migrates complete and partially-removed blocks written by Poshify 1.0' {
            InModuleScope Poshify {
                $legacy = "# Poshify Theme - Generated by Poshify Module`n# Theme: agnoster`n# Generated on: 2025-01-01 10:00:00`n`noh-my-posh init pwsh --config `"C:\t\agnoster.omp.json`" | Invoke-Expression"
                # What the 1.0 cleanup regex left behind: the header line removed, the rest kept
                $leftover = "# Theme: atomic`n# Generated on: 2025-01-02 10:00:00`n`noh-my-posh init pwsh --config `"C:\t\atomic.omp.json`" | Invoke-Expression"
                $content = "Import-Module posh-git`n`n$leftover`n`n$legacy`n"

                $result = Merge-PoshifyProfileBlock -Content $content -Remove
                $result | Should -BeExactly "Import-Module posh-git`n"
            }
        }

        It 'only removes its own block and leaves other oh-my-posh setup intact' {
            InModuleScope Poshify {
                $foreign = '& ([ScriptBlock]::Create((oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json") -join "`n"))'
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                Merge-PoshifyProfileBlock -Content "$foreign`n`n$block`n" -Remove | Should -BeExactly "$foreign`n"
            }
        }

        It 'preserves CRLF line endings' {
            InModuleScope Poshify {
                $result = Merge-PoshifyProfileBlock -Content "Import-Module posh-git`r`n"
                ($result -replace "`r`n", '') | Should -Not -Match "`n"
            }
        }

        It 'generates a block that runs cleanly when no theme is selected' {
            InModuleScope Poshify {
                $block = Get-PoshifyProfileBlock -NewLine "`n"
                { & ([scriptblock]::Create($block)) } | Should -Not -Throw
            }
        }
    }

    Context 'Get-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:home_ -FileName 'agnoster.omp.json', 'custom.omp.yaml'
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.toml', 'readme.md'
        }

        It 'lists themes from Poshify and oh-my-posh, with downloads shadowing bundled themes' {
            $themes = Get-PoshifyTheme
            $themes.Name | Should -Be @('agnoster', 'agnosterplus', 'atomic', 'custom')
            ($themes | Where-Object Name -eq 'agnoster').Source | Should -Be 'Poshify'
        }

        It 'prefers an exact name match over partial matches' {
            $result = @(Get-PoshifyTheme -Name 'agnoster')
            $result.Count | Should -Be 1
            $result[0].Name | Should -Be 'agnoster'
        }

        It 'falls back to substring and wildcard matching' {
            @(Get-PoshifyTheme -Name 'plus').Name | Should -Be 'agnosterplus'
            @(Get-PoshifyTheme -Name 'a*').Count | Should -Be 3
        }

        It 'writes an error when nothing matches' {
            Get-PoshifyTheme -Name 'nope' -ErrorVariable err -ErrorAction SilentlyContinue | Should -BeNullOrEmpty
            $err | Should -Not -BeNullOrEmpty
        }

        It 'tolerates a POSH_THEMES_PATH that does not exist' {
            $env:POSH_THEMES_PATH = Join-Path $TestDrive 'missing'
            { Get-PoshifyTheme -ErrorAction Stop } | Should -Not -Throw
            (Get-PoshifyTheme).Name | Should -Be @('agnoster', 'custom')
        }
    }

    Context 'Set-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json', 'agnosterplus.omp.json', 'atomic.omp.json'
        }

        It 'creates the profile and its directory when missing' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $script:profilePath | Should -Exist
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match '# >>> poshify >>>'
        }

        It 'records the selection and marks the theme as current' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be (Join-Path $script:bundled 'agnoster.omp.json')
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'agnoster'
        }

        It 'does not rewrite the profile when switching themes' {
            Set-PoshifyTheme -Name 'agnoster' -NoApply
            $before = Get-Content -LiteralPath $script:profilePath -Raw
            (Get-Item $script:profilePath).LastWriteTime = [datetime]'2000-01-01'

            Set-PoshifyTheme -Name 'atomic' -NoApply

            Get-Content -LiteralPath $script:profilePath -Raw | Should -BeExactly $before
            (Get-Item $script:profilePath).LastWriteTime | Should -Be ([datetime]'2000-01-01')
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'atomic'
        }

        It 'keeps existing profile content and encoding' {
            New-Item -ItemType Directory -Path (Split-Path $script:profilePath) -Force | Out-Null
            $original = "Write-Output 'héllo wörld'`r`n"
            [IO.File]::WriteAllText($script:profilePath, $original, (New-Object Text.UTF8Encoding($false)))

            Set-PoshifyTheme -Name 'agnoster' -NoApply

            $bytes = [IO.File]::ReadAllBytes($script:profilePath)
            $bytes[0] | Should -Not -Be 0xEF
            $text = [IO.File]::ReadAllText($script:profilePath)
            $text | Should -BeLike "$original`r`n# >>> poshify >>>*"
        }

        It 'refuses an ambiguous partial name instead of guessing' {
            Set-PoshifyTheme -Name 'agnost' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'accepts themes from the pipeline' {
            Get-PoshifyTheme -Name 'atomic' | Set-PoshifyTheme -NoApply
            (Get-PoshifyTheme | Where-Object Current).Name | Should -Be 'atomic'
        }

        It 'accepts a direct path' {
            $custom = Join-Path $TestDrive 'mine.omp.json'
            Set-Content -LiteralPath $custom -Value '{}'
            Set-PoshifyTheme -ThemePath $custom -NoApply
            Get-Content -LiteralPath (Join-Path $script:home_ 'current') | Should -Be $custom
        }

        It 'changes nothing with -WhatIf' {
            Set-PoshifyTheme -Name 'agnoster' -WhatIf
            $script:profilePath | Should -Not -Exist
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'fails when oh-my-posh is not installed' {
            Mock Get-OhMyPoshCommand -ModuleName Poshify { }
            Set-PoshifyTheme -Name 'agnoster' -NoApply -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'not installed'
            $script:profilePath | Should -Not -Exist
        }
    }

    Context 'Reset-PoshifyTheme' {
        BeforeEach {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            New-Item -ItemType Directory -Path (Split-Path $script:profilePath) -Force | Out-Null
            Set-Content -LiteralPath $script:profilePath -Value 'Import-Module posh-git'
            Set-PoshifyTheme -Name 'agnoster' -NoApply
        }

        It 'removes the block and selection, keeping the rest of the profile' {
            Reset-PoshifyTheme
            (Get-Content -LiteralPath $script:profilePath -Raw).Trim() | Should -BeExactly 'Import-Module posh-git'
            Join-Path $script:home_ 'current' | Should -Not -Exist
        }

        It 'warns about oh-my-posh setup it did not create' {
            Add-Content -LiteralPath $script:profilePath -Value 'oh-my-posh init pwsh | Invoke-Expression'
            Reset-PoshifyTheme -WarningVariable warnings -WarningAction SilentlyContinue
            "$warnings" | Should -Match 'outside Poshify'
            Get-Content -LiteralPath $script:profilePath -Raw | Should -Match 'oh-my-posh init pwsh'
        }

        It 'changes nothing with -WhatIf' {
            $before = Get-Content -LiteralPath $script:profilePath -Raw
            Reset-PoshifyTheme -WhatIf
            Get-Content -LiteralPath $script:profilePath -Raw | Should -BeExactly $before
        }
    }

    Context 'Find-PoshifyTheme' {
        BeforeEach {
            Mock Invoke-RestMethod -ModuleName Poshify {
                @(
                    [PSCustomObject]@{ name = 'agnoster.omp.json'; size = 2048; download_url = 'https://example.test/agnoster.omp.json' }
                    [PSCustomObject]@{ name = 'agnosterplus.omp.json'; size = 2048; download_url = 'https://example.test/agnosterplus.omp.json' }
                    [PSCustomObject]@{ name = 'atomic.omp.yaml'; size = 1024; download_url = 'https://example.test/atomic.omp.yaml' }
                    [PSCustomObject]@{ name = 'schema.json'; size = 10; download_url = 'https://example.test/schema.json' }
                )
            }
        }

        It 'returns only theme files' {
            (Find-PoshifyTheme).Name | Should -Be @('agnoster', 'agnosterplus', 'atomic')
        }

        It 'returns a single match' {
            $result = @(Find-PoshifyTheme -Name 'atomic')
            $result.Count | Should -Be 1
            $result[0].FileName | Should -Be 'atomic.omp.yaml'
        }

        It 'reports GitHub rate limiting clearly' {
            Mock Invoke-RestMethod -ModuleName Poshify { throw 'API rate limit exceeded for 1.2.3.4' }
            Find-PoshifyTheme -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'rate limit reached'
        }
    }

    Context 'Install-PoshifyTheme' {
        BeforeEach {
            Mock Find-PoshifyTheme -ModuleName Poshify {
                foreach ($name in 'agnoster', 'agnosterplus', 'atomic') {
                    [PSCustomObject]@{ Name = $name; FileName = "$name.omp.json"; DownloadUrl = "https://example.test/$name.omp.json" }
                }
            }
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value '{}' }
        }

        It 'downloads the exact match without prompting' {
            $theme = Install-PoshifyTheme -Name 'agnoster'
            $theme.Name | Should -Be 'agnoster'
            $theme.Source | Should -Be 'Poshify'
            Join-Path $script:home_ 'agnoster.omp.json' | Should -Exist
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 1 -Exactly
        }

        It 'errors on an ambiguous name instead of prompting' {
            Install-PoshifyTheme -Name 'agnost' -ErrorVariable err -ErrorAction SilentlyContinue
            "$err" | Should -Match 'ambiguous'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly
        }

        It 'returns an existing local theme unless -Force is used' {
            New-ThemeFile -Directory $script:bundled -FileName 'agnoster.omp.json'
            (Install-PoshifyTheme -Name 'agnoster' -WarningAction SilentlyContinue).Source | Should -Be 'oh-my-posh'
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 0 -Exactly

            (Install-PoshifyTheme -Name 'agnoster' -Force).Source | Should -Be 'Poshify'
        }

        It 'is not fooled by a local theme that only contains the name' {
            New-ThemeFile -Directory $script:bundled -FileName 'agnosterplus.omp.json'
            (Install-PoshifyTheme -Name 'agnoster').Name | Should -Be 'agnoster'
        }

        It 'leaves no partial file when the download fails' {
            Mock Invoke-WebRequest -ModuleName Poshify { Set-Content -LiteralPath $OutFile -Value 'partial'; throw 'connection reset' }
            Install-PoshifyTheme -Name 'atomic' -ErrorAction SilentlyContinue
            Get-ChildItem -LiteralPath $script:home_ | Should -BeNullOrEmpty
        }

        It 'queries GitHub once for piped themes' {
            [PSCustomObject]@{ Name = 'agnoster' }, [PSCustomObject]@{ Name = 'atomic' } | Install-PoshifyTheme
            Should -Invoke Find-PoshifyTheme -ModuleName Poshify -Times 1 -Exactly
            Should -Invoke Invoke-WebRequest -ModuleName Poshify -Times 2 -Exactly
        }
    }
}
